/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.view;

import br.edu.unifei.bd.jogo.HabHum;
import br.edu.unifei.bd.jogo.Humanoide;
import br.edu.unifei.dao.jogo.DataSource;
import br.edu.unifei.dao.jogo.HumanoideDao;
import java.lang.reflect.Method;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tercio
 */
public class HumanoideFrame extends javax.swing.JFrame {

    private HumanoideDao hdao = new HumanoideDao(DataSource.createEntityManager());
    private Humanoide jogador;
    private int codTemp;
    private HabHum habilidade = new HabHum();
    
    /**
     * Creates new form HumanoideFrame
     */
    public HumanoideFrame() {
        initComponents();
        NumerosRandomicosDistintos.sortear();
        List<String> l = hdao.buscaNomes();
        
        //Atributos
         lblLv.setVisible(false);
        lblHP.setVisible(false);
        lblMP.setVisible(false);
        lblAtk.setVisible(false);
        lblDef.setVisible(false);
        lblMAtk.setVisible(false);
        lblMDef.setVisible(false);
        txtHP.setVisible(false);
        txtMP.setVisible(false);
        txtAtk.setVisible(false);
        txtDef.setVisible(false);
        txtMAtk.setVisible(false);
        txtMDef.setVisible(false);
        txtLv.setVisible(false);
        
        //Habilidades
        lblHab1.setVisible(false);
        lblHab2.setVisible(false);
        lblHab3.setVisible(false);
        lblDano1.setVisible(false);
        lblDano2.setVisible(false);
        lblDano3.setVisible(false);
        txtHab1.setVisible(false);
        txtHab2.setVisible(false);
        txtHab3.setVisible(false);
        txtDano1.setVisible(false);
        txtDano2.setVisible(false);
        txtDano3.setVisible(false);
        
        for (String a : l) {
            cbxNome.addItem(a);
        }
        if (cbxNome.getItemCount() == 0) {
            cbxNome.setEnabled(false);
            btnEscolher.setEnabled(false);
            btnAtributo.setVisible(false);
            btnAlterar.setVisible(false);
            btnApagar.setVisible(false);
            btnConfirmar.setVisible(false);
            btnCancelar.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        internalHumanoide = new javax.swing.JInternalFrame();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        cbxNome = new javax.swing.JComboBox<>();
        lblPersonagem = new javax.swing.JLabel();
        btnEscolher = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnAtributo = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        txtHP = new javax.swing.JTextField();
        txtMP = new javax.swing.JTextField();
        txtAtk = new javax.swing.JTextField();
        txtDef = new javax.swing.JTextField();
        txtMAtk = new javax.swing.JTextField();
        txtMDef = new javax.swing.JTextField();
        lblHP = new javax.swing.JLabel();
        lblMP = new javax.swing.JLabel();
        lblAtk = new javax.swing.JLabel();
        lblDef = new javax.swing.JLabel();
        lblMAtk = new javax.swing.JLabel();
        lblMDef = new javax.swing.JLabel();
        lblLv = new javax.swing.JLabel();
        txtLv = new javax.swing.JTextField();
        btnHabilidade = new javax.swing.JButton();
        lblHab1 = new javax.swing.JLabel();
        lblHab2 = new javax.swing.JLabel();
        lblHab3 = new javax.swing.JLabel();
        txtHab1 = new javax.swing.JTextField();
        txtHab2 = new javax.swing.JTextField();
        txtHab3 = new javax.swing.JTextField();
        lblDano1 = new javax.swing.JLabel();
        lblDano2 = new javax.swing.JLabel();
        lblDano3 = new javax.swing.JLabel();
        txtDano1 = new javax.swing.JTextField();
        txtDano2 = new javax.swing.JTextField();
        txtDano3 = new javax.swing.JTextField();
        btnLvlUP = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        internalHumanoide.setTitle("Humanoide");
        internalHumanoide.setVisible(true);

        lblNome.setText("Nome:");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.setEnabled(false);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        lblPersonagem.setText("Personagem:");

        btnEscolher.setText("Escolher");
        btnEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherActionPerformed(evt);
            }
        });

        btnCancelar.setText("Voltar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar Nome");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnAtributo.setText("Atributos");
        btnAtributo.setEnabled(false);
        btnAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtributoActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        txtHP.setEnabled(false);

        txtMP.setEnabled(false);

        txtAtk.setEnabled(false);

        txtDef.setEnabled(false);

        txtMAtk.setEnabled(false);

        txtMDef.setEnabled(false);

        lblHP.setText("HP");

        lblMP.setText("MP");

        lblAtk.setText("Atk");

        lblDef.setText("Def");

        lblMAtk.setText("MAtk");

        lblMDef.setText("MDef");

        lblLv.setText("Lv");

        txtLv.setEnabled(false);

        btnHabilidade.setText("Habilidade");
        btnHabilidade.setEnabled(false);
        btnHabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilidadeActionPerformed(evt);
            }
        });

        lblHab1.setText("Hab1:");

        lblHab2.setText("Hab2:");

        lblHab3.setText("Hab3:");

        txtHab1.setEnabled(false);

        txtHab2.setEnabled(false);

        txtHab3.setEnabled(false);

        lblDano1.setText("Dano1:");

        lblDano2.setText("Dano2:");

        lblDano3.setText("Dano3:");

        txtDano1.setEnabled(false);

        txtDano2.setEnabled(false);

        txtDano3.setEnabled(false);

        btnLvlUP.setText("Level Up!");
        btnLvlUP.setEnabled(false);
        btnLvlUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLvlUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internalHumanoideLayout = new javax.swing.GroupLayout(internalHumanoide.getContentPane());
        internalHumanoide.getContentPane().setLayout(internalHumanoideLayout);
        internalHumanoideLayout.setHorizontalGroup(
            internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalHumanoideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(internalHumanoideLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCriar)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(internalHumanoideLayout.createSequentialGroup()
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalHumanoideLayout.createSequentialGroup()
                                .addComponent(lblAtk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addComponent(btnAtributo)
                                .addGap(26, 26, 26)))
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblMP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addComponent(txtDef, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMAtk)))
                        .addGap(18, 18, 18)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addComponent(lblMDef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMDef, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addComponent(lblLv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(internalHumanoideLayout.createSequentialGroup()
                        .addComponent(btnHabilidade)
                        .addGap(18, 18, 18)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(internalHumanoideLayout.createSequentialGroup()
                                        .addComponent(lblHab1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHab1))
                                    .addGroup(internalHumanoideLayout.createSequentialGroup()
                                        .addComponent(lblHab2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHab2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDano1)
                                    .addComponent(lblDano2)))
                            .addGroup(internalHumanoideLayout.createSequentialGroup()
                                .addComponent(lblHab3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHab3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDano3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDano3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(txtDano1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDano2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, internalHumanoideLayout.createSequentialGroup()
                            .addComponent(lblPersonagem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLvlUP))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, internalHumanoideLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnEscolher)
                            .addGap(41, 41, 41)
                            .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnConfirmar)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        internalHumanoideLayout.setVerticalGroup(
            internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalHumanoideLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addComponent(btnCriar)
                .addGap(18, 18, 18)
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(internalHumanoideLayout.createSequentialGroup()
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersonagem)
                            .addComponent(btnLvlUP))
                        .addGap(18, 18, 18)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEscolher)
                            .addComponent(btnAlterar)
                            .addComponent(btnConfirmar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnApagar)
                            .addComponent(btnCancelar))
                        .addGap(21, 21, 21)
                        .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHP))
                            .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMP)
                                .addComponent(lblLv)
                                .addComponent(txtLv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnAtributo))
                .addGap(18, 18, 18)
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtk)
                    .addComponent(lblMDef)
                    .addComponent(lblMAtk)
                    .addComponent(lblDef))
                .addGap(18, 18, 18)
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabilidade)
                    .addComponent(lblHab1)
                    .addComponent(txtHab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDano1)
                    .addComponent(txtDano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDano2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHab2)
                        .addComponent(txtHab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(internalHumanoideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHab3)
                    .addComponent(txtHab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDano3)
                    .addComponent(txtDano3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalHumanoide, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalHumanoide)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        Humanoide h = new Humanoide();
        h.setNome(txtNome.getText());
        List<Integer> listaCodAleatorio = hdao.findAllCodAleatorio();        
        h.setCodAleatorio(NumerosRandomicosDistintos.getList().get(NumerosRandomicosDistintos.getNumAleatorio()));
        for ( int i = 0; i < listaCodAleatorio.size(); i++ ) {
            if(h.getCodAleatorio() == listaCodAleatorio.get(i)){
                h.setCodAleatorio( NumerosRandomicosDistintos.getList().get( NumerosRandomicosDistintos.getNumAleatorio() ) );
                i = 0;
                continue;
            }
            i++;
        }
        codTemp = h.getCodAleatorio();
        cbxNome.addItem(h.getNome());
        hdao.create(h);
        JOptionPane.showMessageDialog(this,
                "Personagem criado com sucesso!");
        txtNome.setText("");
        if (cbxNome.getItemCount() != 0) {
            cbxNome.setEnabled(true);
            btnEscolher.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherActionPerformed
//        Method m;
//        try {
//            m = cbxNome.getSelectedItem().getClass().getMethod("getCodAleatorio");
//        } catch (NoSuchMethodException ex) {
//            Logger.getLogger(HumanoideFrame.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SecurityException ex) {
//            Logger.getLogger(HumanoideFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        Integer inteiro = (Integer) m.invoke(cbxNome.getSelectedItem().getClass(), null);
//        String n = cbxNome.getSelectedItem().getClass().getName();
 //       System.out.println(n);
 // codTemp
        Integer chave
                = hdao.findKey(cbxNome.getSelectedItem().toString());
        jogador = hdao.findByKeyH(chave);
        btnAtributo.setVisible(true);
        btnAlterar.setVisible(true);
        btnApagar.setVisible(true);
        btnConfirmar.setVisible(true);
        btnCancelar.setVisible(true);
        btnHabilidade.setVisible(true);
        btnAtributo.setEnabled(true);
        cbxNome.setEnabled(false);
        btnCriar.setEnabled(false);
        txtNome.setEnabled(false);
        btnApagar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEscolher.setEnabled(false);
        txtNome.setText(jogador.getNome());
        btnAlterar.setEnabled(true);
        btnConfirmar.setEnabled(false);
        btnHabilidade.setEnabled(true);
        btnLvlUP.setEnabled(true);
        JOptionPane.showMessageDialog(this,
                "Personagem selecionado.");
  
    }//GEN-LAST:event_btnEscolherActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        hdao.delete(jogador);
        JOptionPane.showMessageDialog(this,
                "Personagem deletado!");
        txtNome.setText("");
        txtNome.setEnabled(true);
        btnCriar.setEnabled(true);
        cbxNome.removeItem(cbxNome.getSelectedItem());
        cbxNome.setEnabled(true);
        btnEscolher.setEnabled(true);
        if (cbxNome.getItemCount() == 0) {
            cbxNome.setEnabled(false);
            btnEscolher.setEnabled(false);
            btnAtributo.setVisible(false);
            btnAlterar.setVisible(false);
            btnApagar.setVisible(false);
            btnConfirmar.setVisible(false);
            btnCancelar.setVisible(false);
            btnHabilidade.setVisible(false);
        }
        btnApagar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnAtributo.setEnabled(false);
        btnLvlUP.setEnabled(false);
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jogador = null;
        
        txtNome.setText("");
        txtAtk.setText("");
        txtDef.setText("");
        txtHP.setText("");
        txtMP.setText("");
        txtMAtk.setText("");
        txtMDef.setText("");
        txtLv.setText("");
        
        txtHab1.setText("");
        txtHab2.setText("");
        txtHab3.setText("");
        txtDano1.setText("");
        txtDano2.setText("");
        txtDano3.setText("");
        
        txtNome.setEnabled(true);
        btnCriar.setEnabled(true);
        cbxNome.setEnabled(true);
        btnEscolher.setEnabled(true);
        btnApagar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnAtributo.setEnabled(false);
        btnHabilidade.setEnabled(false);
        btnLvlUP.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        txtNome.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnConfirmar.setEnabled(true);
        btnAtributo.setEnabled(false);
        btnHabilidade.setEnabled(false);
        btnLvlUP.setEnabled(false);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        cbxNome.removeItem(jogador.getNome());
        jogador.setNome(txtNome.getText());
        cbxNome.addItem(jogador.getNome());
        hdao.update(jogador);
        JOptionPane.showMessageDialog(this,
                "Nome atualizado!");
        txtNome.setText("");
        txtNome.setEnabled(true);
        btnCriar.setEnabled(true);
        cbxNome.setEnabled(true);
        btnEscolher.setEnabled(true);
        jogador = null;
        btnAlterar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnAtributo.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnHabilidade.setEnabled(false);
        btnLvlUP.setEnabled(false);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtributoActionPerformed
        lblHP.setVisible(true);
        lblMP.setVisible(true);
        lblAtk.setVisible(true);
        lblDef.setVisible(true);
        lblMAtk.setVisible(true);
        lblMDef.setVisible(true);
        lblLv.setVisible(true);
        txtHP.setVisible(true);
        txtMP.setVisible(true);
        txtAtk.setVisible(true);
        txtDef.setVisible(true);
        txtMAtk.setVisible(true);
        txtMDef.setVisible(true);
        txtLv.setVisible(true);
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnAtributo.setEnabled(false);
        btnHabilidade.setEnabled(true);
        btnLvlUP.setEnabled(true);
        txtHP.setText( String.valueOf( jogador.getHP1() ) );
        txtMP.setText( String.valueOf( jogador.getMP1() ) );
        txtAtk.setText( String.valueOf( jogador.getAtaque1() ) );
        txtDef.setText( String.valueOf( jogador.getDefesa1() ) );
        txtMAtk.setText( String.valueOf(0) );
        txtMDef.setText( String.valueOf( jogador.getDefMagia1() ) );
        txtLv.setText( String.valueOf(jogador.getLevelAtual() ) );
    }//GEN-LAST:event_btnAtributoActionPerformed

    private void btnHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidadeActionPerformed
        lblHab1.setVisible(true);
        lblHab2.setVisible(true);
        lblHab3.setVisible(true);
        lblDano1.setVisible(true);
        lblDano2.setVisible(true);
        lblDano3.setVisible(true);
        txtHab1.setVisible(true);
        txtHab2.setVisible(true);
        txtHab3.setVisible(true);
        txtDano1.setVisible(true);
        txtDano2.setVisible(true);
        txtDano3.setVisible(true);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnHabilidade.setEnabled(false);
        btnAtributo.setEnabled(true);
        btnLvlUP.setEnabled(true);
        
        
        txtHab1.setText( String.valueOf( HabHum.class.getDeclaredFields()[0].getName() ) );
        txtHab2.setText( String.valueOf( HabHum.class.getDeclaredFields()[1].getName() ) );
        txtHab3.setText( String.valueOf( HabHum.class.getDeclaredFields()[2].getName() ) );
        txtDano1.setText( String.valueOf( habilidade.getFilosofar()) );
        txtDano2.setText( String.valueOf( habilidade.getDrinkMaconha()));
        txtDano3.setText( String.valueOf( 0 ));
    }//GEN-LAST:event_btnHabilidadeActionPerformed

    private void btnLvlUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLvlUPActionPerformed
        jogador.setLevelAtual(jogador.getLevelAtual()+1);
        jogador.setHP1(jogador.getHP1()+NumerosRandomicos.randomInt(0, 3)+1);
        jogador.setMP1(jogador.getMP1()+NumerosRandomicos.randomInt(0, 3));
        jogador.setAtaque1(jogador.getAtaque1()+NumerosRandomicos.randomInt(0, 3)+1);
        jogador.setDefesa1(jogador.getDefesa1()+NumerosRandomicos.randomInt(0, 3));
        jogador.setDefMagia1(jogador.getDefMagia1()+NumerosRandomicos.randomInt(0, 3));
        hdao.update(jogador);
               JOptionPane.showMessageDialog(this,
                "Level Up!");
        btnAtributo.setEnabled(true);
        btnAtributo.doClick();
    }//GEN-LAST:event_btnLvlUPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HumanoideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HumanoideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HumanoideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HumanoideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanoideFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnAtributo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEscolher;
    private javax.swing.JButton btnHabilidade;
    private javax.swing.JButton btnLvlUP;
    private javax.swing.JComboBox<String> cbxNome;
    private javax.swing.JInternalFrame internalHumanoide;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAtk;
    private javax.swing.JLabel lblDano1;
    private javax.swing.JLabel lblDano2;
    private javax.swing.JLabel lblDano3;
    private javax.swing.JLabel lblDef;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblHab1;
    private javax.swing.JLabel lblHab2;
    private javax.swing.JLabel lblHab3;
    private javax.swing.JLabel lblLv;
    private javax.swing.JLabel lblMAtk;
    private javax.swing.JLabel lblMDef;
    private javax.swing.JLabel lblMP;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPersonagem;
    private javax.swing.JTextField txtAtk;
    private javax.swing.JTextField txtDano1;
    private javax.swing.JTextField txtDano2;
    private javax.swing.JTextField txtDano3;
    private javax.swing.JTextField txtDef;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtHab1;
    private javax.swing.JTextField txtHab2;
    private javax.swing.JTextField txtHab3;
    private javax.swing.JTextField txtLv;
    private javax.swing.JTextField txtMAtk;
    private javax.swing.JTextField txtMDef;
    private javax.swing.JTextField txtMP;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
