/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.view;

import br.edu.unifei.bd.jogo.Exatoide;
import br.edu.unifei.bd.jogo.Humanoide;
import br.edu.unifei.bd.jogo.Inimigo;
import br.edu.unifei.dao.jogo.DataSource;
import br.edu.unifei.dao.jogo.HumanoideDao;
import br.edu.unifei.dao.jogo.InimigoDao;
import br.edu.unifei.dao.jogo.ExatoideDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Tercio
 */
public class JogoFrame extends javax.swing.JFrame {

    private ExatoideDao edao = new ExatoideDao(DataSource.createEntityManager());
    private HumanoideDao hdao = new HumanoideDao(DataSource.createEntityManager());
    private Exatoide jogador1;
    private Humanoide jogador2;
    /**
     * Creates new form JogoFrame
     */
    public JogoFrame() {
        initComponents();
        //List<String> listaInimigo = bdao.buscarNomesInimigos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        cbx1 = new javax.swing.JComboBox<>();
        cbx2 = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnLutar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPersonagem = new javax.swing.JMenu();
        humanoide = new javax.swing.JMenuItem();
        exatoide = new javax.swing.JMenuItem();
        professor = new javax.swing.JMenuItem();
        mnuMonstros = new javax.swing.JMenu();
        mnuBatalha = new javax.swing.JMenu();
        mnuPvP = new javax.swing.JMenuItem();
        mnuMvP = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx1.setEnabled(false);

        cbx2.setEnabled(false);

        txt2.setForeground(new java.awt.Color(0, 204, 204));
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setEnabled(false);

        txt1.setForeground(new java.awt.Color(0, 255, 0));
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setEnabled(false);

        btn1.setText("Confirmar");
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Confirmar");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnLutar.setText("Lutar");
        btnLutar.setEnabled(false);
        btnLutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLutarActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 102, 0));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setEnabled(false);

        mnuPersonagem.setText("Personagem");

        humanoide.setText("Humanoide");
        humanoide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humanoideActionPerformed(evt);
            }
        });
        mnuPersonagem.add(humanoide);

        exatoide.setText("Exatoide");
        exatoide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exatoideActionPerformed(evt);
            }
        });
        mnuPersonagem.add(exatoide);

        professor.setText("Professor");
        professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorActionPerformed(evt);
            }
        });
        mnuPersonagem.add(professor);

        jMenuBar1.add(mnuPersonagem);

        mnuMonstros.setText("Monstro");
        mnuMonstros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMonstrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuMonstros);

        mnuBatalha.setText("Batalha");

        mnuPvP.setText("PvP");
        mnuPvP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPvPActionPerformed(evt);
            }
        });
        mnuBatalha.add(mnuPvP);

        mnuMvP.setText("MvP");
        mnuMvP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMvPActionPerformed(evt);
            }
        });
        mnuBatalha.add(mnuMvP);

        jMenuBar1.add(mnuBatalha);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn1)
                        .addGap(171, 171, 171)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnLutar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnLutar)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void humanoideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humanoideActionPerformed
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HumanoideFrame().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_humanoideActionPerformed

    private void exatoideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exatoideActionPerformed
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExatoideFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_exatoideActionPerformed

    private void professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorActionPerformed
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_professorActionPerformed

    private void mnuMonstrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMonstrosMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonstroFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_mnuMonstrosMouseClicked

    private void mnuPvPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPvPActionPerformed
        List<String> listaPersonagem1 = edao.buscaNomes();
        List<String> listaPersonagem2 = hdao.buscaNomes();
        for (String a : listaPersonagem1) {
            cbx1.addItem(a);
        }
        for (String a : listaPersonagem2) {
            cbx2.addItem(a);
        }
        
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        cbx1.setEnabled(true);
        cbx2.setEnabled(true);
        txtTitulo.setText("PvP");
        txt1.setText("Player 1: Exatoide");
        txt2.setText("Player 2: Humanoide");
    }//GEN-LAST:event_mnuPvPActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       
        Integer chave
                = edao.findKey(cbx1.getSelectedItem().toString());
        jogador1 = edao.findByKeyH(chave);

        btn1.setEnabled(false);
        cbx1.setEnabled(false);
        btnLutar.setEnabled(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        Integer chave
                = hdao.findKey(cbx2.getSelectedItem().toString());
        jogador2 = hdao.findByKeyH(chave);

        btn2.setEnabled(false);
        cbx2.setEnabled(false);
        btnLutar.setEnabled(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnLutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLutarActionPerformed
        int HP2Tot = jogador1.getHP2();
        int HP1Tot = jogador2.getHP1();
        
        while(jogador1.getHP2() > 0 && jogador2.getHP1() > 0 ){
            if(jogador2.getHP1() - jogador1.getAtaque2() < 0){
                jogador2.setHP1(0);
            }else{
            jogador2.setHP1(jogador2.getHP1() - jogador1.getAtaque2());
            }
            JOptionPane.showMessageDialog(this,
                    "(" + jogador2.getNome() + ") HP: " + jogador2.getHP1()
                    + "/" + HP1Tot);
            if(jogador2.getHP1() - jogador1.getAtaque2() < 0){
                break;
            }
            
            if(jogador1.getHP2() - jogador2.getAtaque1() < 0){
                jogador1.setHP2(0);
            }else{
            jogador1.setHP2(jogador1.getHP2() - jogador2.getAtaque1());
            }
            
            JOptionPane.showMessageDialog(this,
                    "(" + jogador1.getNome() + ") HP: " + jogador1.getHP2()
                    + "/" + HP2Tot);
            
        }
        if(jogador1.getHP2() > jogador2.getHP1()){
            JOptionPane.showMessageDialog(this,jogador1.getNome()+ " venceu!");
            int x = NumerosRandomicos.randomInt(0, 3);
            switch(x){
                    case 0: JOptionPane.showMessageDialog(this,jogador1.getNome()+ " ganhou +2 de HP!");
                            jogador1.setHP2(jogador1.getHP2()+2);
                            edao.update(jogador1);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                            
                    case 1: JOptionPane.showMessageDialog(this,jogador1.getNome()+ " ganhou +2 de MP!");
                            jogador1.setMP2(jogador1.getMP2()+2);
                            edao.update(jogador1);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                            
                    case 2: JOptionPane.showMessageDialog(this,jogador1.getNome()+ " ganhou +2 de DEF!");
                            jogador1.setDefesa2(jogador1.getDefesa2()+2);
                            edao.update(jogador1);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                            
                    case 3: JOptionPane.showMessageDialog(this,jogador1.getNome()+ " ganhou +2 de ATK!");
                            jogador1.setAtaque2(jogador1.getAtaque2()+2);
                            edao.update(jogador1);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
            }    
        }
        else{ 
            JOptionPane.showMessageDialog(this,jogador2.getNome()+ " venceu!");
                        int x = NumerosRandomicos.randomInt(0, 3);
            switch(x){
                    case 0: JOptionPane.showMessageDialog(this,jogador2.getNome()+ " ganhou +2 de HP!");
                            jogador2.setHP1(jogador2.getHP1()+2);
                            hdao.update(jogador2);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                            
                    case 1: JOptionPane.showMessageDialog(this,jogador2.getNome()+ " ganhou +2 de MP!");
                            jogador2.setMP1(jogador2.getMP1()+2);
                            hdao.update(jogador2);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                            
                    case 2: JOptionPane.showMessageDialog(this,jogador2.getNome()+ " ganhou +2 de DEF!");
                            jogador2.setDefesa1(jogador2.getDefesa1()+2);
                            hdao.update(jogador2);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                            
                    case 3: JOptionPane.showMessageDialog(this,jogador2.getNome()+ " ganhou +2 de ATK!");
                            jogador2.setAtaque1(jogador2.getAtaque1()+2);
                            hdao.update(jogador2);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
            }
        }
        btnLutar.setEnabled(false);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        cbx1.setEnabled(true);
        cbx2.setEnabled(true);
    }//GEN-LAST:event_btnLutarActionPerformed

    private void mnuMvPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMvPActionPerformed
              java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MvPFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_mnuMvPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnLutar;
    private javax.swing.JComboBox<String> cbx1;
    private javax.swing.JComboBox<String> cbx2;
    private javax.swing.JMenuItem exatoide;
    private javax.swing.JMenuItem humanoide;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuBatalha;
    private javax.swing.JMenu mnuMonstros;
    private javax.swing.JMenuItem mnuMvP;
    private javax.swing.JMenu mnuPersonagem;
    private javax.swing.JMenuItem mnuPvP;
    private javax.swing.JMenuItem professor;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
