/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.view;

import br.edu.unifei.bd.jogo.Inimigo;
import br.edu.unifei.dao.jogo.BossDao;
import br.edu.unifei.dao.jogo.DataSource;
import br.edu.unifei.dao.jogo.InimigoDao;
import java.util.List;

/**
 *
 * @author Tercio
 */
public class MonstroFrame extends javax.swing.JFrame {

    private InimigoDao idao = new InimigoDao(DataSource.createEntityManager());
    private Inimigo adversario;
    //private BossDao bdao = new BossDao(DataSource.createEntityManager());    
            /**
     * Creates new form MonstroFrame
     */
    public MonstroFrame() {
        initComponents();
        List<String> listaInimigo = idao.buscaNomes();
        for (String a : listaInimigo) {
            cbxMonstro.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalMonstro = new javax.swing.JInternalFrame();
        lblNome = new javax.swing.JLabel();
        cbxMonstro = new javax.swing.JComboBox<>();
        btnPesquisar = new javax.swing.JButton();
        btnAtributo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblHP = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        lblMP = new javax.swing.JLabel();
        txtMP = new javax.swing.JTextField();
        lblAtk = new javax.swing.JLabel();
        txtAtk = new javax.swing.JTextField();
        lblDef = new javax.swing.JLabel();
        txtDef = new javax.swing.JTextField();
        lblMAtk = new javax.swing.JLabel();
        txtMAtk = new javax.swing.JTextField();
        lblMDef = new javax.swing.JLabel();
        txtMDef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        internalMonstro.setTitle("Monstro");
        internalMonstro.setVisible(true);

        lblNome.setText("Nome");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAtributo.setText("Atributos");
        btnAtributo.setEnabled(false);
        btnAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtributoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Voltar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblHP.setText("HP");

        txtHP.setEnabled(false);

        lblMP.setText("MP");

        txtMP.setEnabled(false);

        lblAtk.setText("Atk");

        txtAtk.setEnabled(false);

        lblDef.setText("Def");

        txtDef.setEnabled(false);

        lblMAtk.setText("MAtk");

        txtMAtk.setEnabled(false);

        lblMDef.setText("MDef");

        txtMDef.setEnabled(false);

        javax.swing.GroupLayout internalMonstroLayout = new javax.swing.GroupLayout(internalMonstro.getContentPane());
        internalMonstro.getContentPane().setLayout(internalMonstroLayout);
        internalMonstroLayout.setHorizontalGroup(
            internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalMonstroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtributo)
                    .addGroup(internalMonstroLayout.createSequentialGroup()
                        .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(internalMonstroLayout.createSequentialGroup()
                                .addComponent(lblHP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lblAtk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(internalMonstroLayout.createSequentialGroup()
                                .addComponent(lblMP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lblDef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDef, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(internalMonstroLayout.createSequentialGroup()
                                .addComponent(lblMAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMAtk))
                            .addGroup(internalMonstroLayout.createSequentialGroup()
                                .addComponent(lblMDef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMDef, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(internalMonstroLayout.createSequentialGroup()
                            .addComponent(lblNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxMonstro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(internalMonstroLayout.createSequentialGroup()
                            .addComponent(btnPesquisar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(132, 132, 132))
        );
        internalMonstroLayout.setVerticalGroup(
            internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalMonstroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMonstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(btnCancelar))
                .addGap(27, 27, 27)
                .addComponent(btnAtributo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHP)
                    .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtk)
                    .addComponent(txtAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMAtk)
                    .addComponent(txtMAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMP)
                    .addGroup(internalMonstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDef)
                        .addComponent(txtDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMDef)
                        .addComponent(txtMDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalMonstro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalMonstro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        adversario = null;
        
        txtAtk.setText("");
        txtDef.setText("");
        txtHP.setText("");
        txtMP.setText("");
        txtMAtk.setText("");
        txtMDef.setText("");
        
        btnPesquisar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnAtributo.setEnabled(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
                Integer chave
                = idao.findKey(cbxMonstro.getSelectedItem().toString());
        adversario = idao.findByKeyH(chave);
        
        btnPesquisar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnAtributo.setEnabled(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtributoActionPerformed
        txtHP.setText( String.valueOf( adversario.getHP4() ) );
        txtMP.setText( String.valueOf( adversario.getMP4() ) );
        txtAtk.setText( String.valueOf( adversario.getAtaque4() ) );
        txtDef.setText( String.valueOf( adversario.getDefesa4() ) );
        txtMAtk.setText( String.valueOf(adversario.getMagia4()) );
        txtMDef.setText( String.valueOf( adversario.getDefMagia4() ) );

        btnAtributo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnAtributoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonstroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonstroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonstroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonstroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonstroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtributo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxMonstro;
    private javax.swing.JInternalFrame internalMonstro;
    private javax.swing.JLabel lblAtk;
    private javax.swing.JLabel lblDef;
    private javax.swing.JLabel lblHP;
    private javax.swing.JLabel lblMAtk;
    private javax.swing.JLabel lblMDef;
    private javax.swing.JLabel lblMP;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtAtk;
    private javax.swing.JTextField txtDef;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtMAtk;
    private javax.swing.JTextField txtMDef;
    private javax.swing.JTextField txtMP;
    // End of variables declaration//GEN-END:variables
}
