/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifei.view;

import br.edu.unifei.bd.jogo.Inimigo;
import br.edu.unifei.bd.jogo.Professor;
import br.edu.unifei.dao.jogo.DataSource;
import br.edu.unifei.dao.jogo.InimigoDao;
import br.edu.unifei.dao.jogo.ProfessorDao;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Tercio
 */
public class MvPFrame extends javax.swing.JFrame {

    private ProfessorDao pdao = new ProfessorDao(DataSource.createEntityManager());
    private InimigoDao idao = new InimigoDao(DataSource.createEntityManager());
    private Professor jogador;
    private Inimigo adversario;
    /**
     * Creates new form JogoFrame
     */
    public MvPFrame() {
        initComponents();
                List<String> listaPersonagem = pdao.buscaNomes();
        List<String> listaInimigo = idao.buscaNomes();
        for (String a : listaPersonagem) {
            cbx1.addItem(a);
        }
        for (String a : listaInimigo) {
            cbx2.addItem(a);
        }
        
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        cbx1.setEnabled(true);
        cbx2.setEnabled(true);
        txtTitulo.setText("MvP");
        txt1.setText("Player: Professor");
        txt2.setText("Adversário: Inimigo");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        cbx1 = new javax.swing.JComboBox<>();
        cbx2 = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnLutar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbx1.setEnabled(false);

        cbx2.setEnabled(false);

        txt2.setForeground(new java.awt.Color(0, 204, 204));
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setEnabled(false);

        txt1.setForeground(new java.awt.Color(0, 255, 0));
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setEnabled(false);

        btn1.setText("Confirmar");
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Confirmar");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnLutar.setText("Lutar");
        btnLutar.setEnabled(false);
        btnLutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLutarActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 102, 0));
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitulo.setEnabled(false);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn1)
                        .addGap(171, 171, 171)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnLutar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2)
                    .addComponent(btn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnLutar)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       
        Integer chave
                = pdao.findKey(cbx1.getSelectedItem().toString());
        jogador = pdao.findByKeyH(chave);

        btn1.setEnabled(false);
        cbx1.setEnabled(false);
        btnLutar.setEnabled(true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        Integer chave
                = idao.findKey(cbx2.getSelectedItem().toString());
        adversario = idao.findByKeyH(chave);

        btn2.setEnabled(false);
        cbx2.setEnabled(false);
        btnLutar.setEnabled(true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnLutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLutarActionPerformed
        int HP3Tot = jogador.getHP3();
        int HP4Tot = adversario.getHP4();
        
        while(jogador.getHP3() > 0 && adversario.getHP4() > 0 ){
            
            if(adversario.getHP4() - jogador.getAtaque3() < 0){
                adversario.setHP4(0);
            }else{
            adversario.setHP4(adversario.getHP4() - jogador.getAtaque3());
            }
            JOptionPane.showMessageDialog(this,
                    "(" + adversario.getNomeInimigo() + ") HP: " + adversario.getHP4()
                    + "/" + HP4Tot);
            if(adversario.getHP4() - jogador.getAtaque3() < 0){
                break;
            }
            if(jogador.getHP3() - adversario.getAtaque4() < 0){
                jogador.setHP3(0);
            }else{
            jogador.setHP3(jogador.getHP3() - adversario.getAtaque4());
            }
            
            JOptionPane.showMessageDialog(this,
                    "(" + jogador.getNome() + ") HP: " + jogador.getHP3()
                    + "/" + HP3Tot);
            
        }
        if(jogador.getHP3() > adversario.getHP4()){
            JOptionPane.showMessageDialog(this,jogador.getNome()+ " venceu!");
            int x = NumerosRandomicos.randomInt(0, 3);
            switch(x){
                    case 0: JOptionPane.showMessageDialog(this,jogador.getNome()+ " ganhou +3 de HP!");
                            jogador.setHP3(jogador.getHP3()+3);
                            pdao.update(jogador);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                    
                    case 1: JOptionPane.showMessageDialog(this,jogador.getNome()+ " ganhou +2 de MP!");
                            jogador.setMP3(jogador.getMP3()+2);
                            pdao.update(jogador);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                    
                    case 2: JOptionPane.showMessageDialog(this,jogador.getNome()+ " ganhou +2 de DEF!");
                            jogador.setDefesa3(jogador.getDefesa3()+2);
                            pdao.update(jogador);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                    
                    case 3: JOptionPane.showMessageDialog(this,jogador.getNome()+ " ganhou +1 de ATK!");
                            jogador.setAtaque3(jogador.getAtaque3()+1);
                            pdao.update(jogador);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
            }    
        }
        else{ 
            JOptionPane.showMessageDialog(this,adversario.getNomeInimigo()+ " venceu!");
                        int x = NumerosRandomicos.randomInt(0, 3);
            switch(x){
                    case 0: JOptionPane.showMessageDialog(this,adversario.getNomeInimigo()+ " ganhou +5 de HP!");
                            adversario.setHP4(adversario.getHP4()+5);
                            idao.update(adversario);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                    
                    case 1: JOptionPane.showMessageDialog(this,adversario.getNomeInimigo()+ " ganhou +6 de MP!");
                            adversario.setMP4(adversario.getMP4()+6);
                            idao.update(adversario);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                    
                    case 2: JOptionPane.showMessageDialog(this,adversario.getNomeInimigo()+ " ganhou +7 de DEF!");
                            adversario.setDefesa4(adversario.getDefesa4()+7);
                            idao.update(adversario);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                    
                    case 3: JOptionPane.showMessageDialog(this,adversario.getNomeInimigo()+ " ganhou +9 de ATK!");
                            adversario.setAtaque4(adversario.getAtaque4()+9);
                            idao.update(adversario);
                            JOptionPane.showMessageDialog(this,"Atributo atualizado!");
                            break;
                
            }
        }
        btnLutar.setEnabled(false);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        cbx1.setEnabled(true);
        cbx2.setEnabled(true);
    }//GEN-LAST:event_btnLutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MvPFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MvPFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MvPFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MvPFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MvPFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnLutar;
    private javax.swing.JComboBox<String> cbx1;
    private javax.swing.JComboBox<String> cbx2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
